"$schema" = 'https://starship.rs/config-schema.json'
palette = "catppuccin_macchiato"
add_newline = true
command_timeout = 2000

format = """
$status\
${custom.git_host}\
$directory\
$git_branch\
$fill\
${custom.since_last_commit}\
$git_state\
$git_commit\
$git_metrics\
$git_status\
$lua\
$nodejs\
$golang\
$java\
$package\
$docker_context\
$cmd_duration\
$line_break\
$character\
"""

[fill]
symbol = " "
style = 'text'
disabled = false

[status]
symbol = ' '
disabled = false
map_symbol = true
style = 'blue'
success_symbol = ''
format = '[$symbol](yellow)$status ($style)'

[directory]
style = "blue"
home_symbol = "~"
truncation_length = 0
fish_style_pwd_dir_length = 1
format = '[$path]($style)[$read_only]($read_only_style) '

[character]
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"
success_symbol = "[[>_](text)](text)"

[git_branch]
style = "text"
symbol = ' '
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
style = "text"
up_to_date = ''
renamed = '👅'
conflicted = '🏳'
behind = '😰 ${count}'
stashed = " ${count} "
staged = '[+$count](green) '
deleted = '󰗨 ${count}(red) '
ahead = '[⇡${count}](lavender) '
modified = '[ ${count}](lavender) '
untracked = "[ ${count}](sapphire) "
diverged = '⇕⇡${ahead_count}⇣${behind_count} '
format = "[[($conflicted$modified$staged$renamed$deleted)](218)($ahead_behind$stashed)]($style)"

[git_state]
style = "text"
cherry_pick = '[🍒PICK](red)'
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[git_metrics]
disabled = false
only_nonzero_diffs = true
format = '[+$added](green)[-$deleted](maroon) '

[cmd_duration]
disabled = false
style = "yellow"
min_time = 10_000
min_time_to_notify = 10000
show_notifications = false
format = "[ ⏰ $duration]($style) "

[lua]
format = '[󰢱 $version](blue) '

[package]
symbol = " "
style = "teal"
disabled = false
display_private = true
format = '[$symbol$version]($style) '

[docker_context]
format = '[ $context](sky) '

[java]
symbol = " "
style = "mauve"
format = '[$symbol($version)]($style) '
detect_extensions = ["java", "class", "jar"]
detect_files = ["pom.xml", "build.gradle", "build.gradle.kts"]

[golang]
symbol = " "
style = "teal"
format = '[$symbol($version)]($style) '
detect_extensions = ["go"]
detect_files = ["go.mod", "go.sum"]

[nodejs]
symbol = ' '
style = "green"
disabled = false
format = '[$symbol($version)]($style) '
detect_files = ['node_modules', 'package.json']
detect_extensions = []

[custom.since_last_commit]
style = "mauve"
directories = [".git"]
format = "[󰚰 $output]($style) "
shell = ["bash", "--norc", "--noprofile"]
description = "Show time since last commit"
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
command = """echo "n/a" """

[custom.git_host]
style = "text"
directories = [".git"]
format = "[$output]($style) "
shell = ["bash", "--norc", "--noprofile"]
description = "Show icon of git host platform"
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
command = """echo "" """

[palettes.catppuccin_macchiato]
bg = "#000000"
background = "#000000"
split = "#000000"
tab_bar_bg = "#000000"
tab_bar_inactive_bg = "#000000"
tab_bar_inactive_fg = "#b7bdf8"
tab_bar_active_bg = "#000000"
tab_bar_active_fg = "#8aadf4"
tab_bar_active_intensity = "Bold"
tab_bar_new_tab_bg = "#000000"
tab_bar_border_left = "#C093B7"
tab_bar_border_right = "#C093B7"
tab_bar_border_top = "#C093B7"
tab_bar_border_bottom = "#C093B7"
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

