return {
  -- -- { "rcarriga/nvim-dap-ui", enabled = false },
  -- {
  --   "miroshQa/debugmaster.nvim",
  --   -- osv is needed if you want to debug neovim lua code. Also can be used
  --   -- as a way to quickly test-drive the plugin without configuring debug adapters
  --   dependencies = { "mfussenegger/nvim-dap", "jbyuki/one-small-step-for-vimkind" },
  --   config = function()
  --     local dm = require("debugmaster")
  --     -- make sure you don't have any other keymaps that starts with "<leader>d" to avoid delay
  --     -- Alternative keybindings to "<leader>d" could be: "<leader>m", "<leader>;"
  --     vim.keymap.set({ "n", "v" }, "<leader>d", dm.mode.toggle, { nowait = true })
  --     -- If you want to disable debug mode in addition to leader+d using the Escape key:
  --     -- vim.keymap.set("n", "<Esc>", dm.mode.disable)
  --     -- This might be unwanted if you already use Esc for ":noh"
  --     vim.keymap.set("t", "<C-\\>", "<C-\\><C-n>", { desc = "Exit terminal mode" })
  --
  --     dm.plugins.osv_integration.enabled = true -- needed if you want to debug neovim lua code
  --     local dap = require("dap")
  --     -- Configure your debug adapters here
  --     -- https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation
  --     -- Load Go adapter
  --     require("plugins.dap.settings.go-debug-adapter")
  --
  --     -- Load Chrome adapter
  --     require("plugins.dap.settings.chrome-debug-adapter")
  --
  --     -- Load Bash adapter
  --     require("plugins.dap.settings.bash-debug-adapter")
  --   end,
  --   keys = {
  --     -- { "<leader>dm", "<cmd>DebugMasterToggle<cr>", desc = "Toggle DebugMaster" },
  --   },
  -- },
  -- {
  --   "igorlfs/nvim-dap-view",
  --   enabled = false, -- Easy to disable if issues arise
  --   event = "VeryLazy",
  --   dependencies = {
  --     "mfussenegger/nvim-dap",
  --   },
  --   opts = {
  --     -- Add any configuration options here
  --   },
  --   keys = {
  --     { "<leader>dv", "<cmd>DapViewToggle<cr>", desc = "Toggle Dap View" },
  --   },
  -- },
}
