[colors]   
background = "#181818"
foreground = "#d8d8d8"
ansi = [
  "#181818",  -- black
  "#e06c75",  -- red  
  "#98c379",  -- green
  "#e5c07b",  -- yellow
  "#61afef",  -- blue
  "#c678dd",  -- purple
  "#56b6c2",  -- cyan
  "#d8d8d8"   -- white
]
brights = {
  "#5c6370",  -- bright black (comment)
  "#e06c75",  -- bright red
  "#98c379",  -- bright green  
  "#e5c07b",  -- bright yellow
  "#61afef",  -- bright blue
  "#c678dd",  -- bright purple
  "#56b6c2",  -- bright cyan
  "#d8d8d8",  -- bright white
}
cursor_bg = "#61afef"
cursor_border = "#61afef"
selection_bg = "#3e4452"
split = "#5c6370"


