return {
  -- {
  --   "williamboman/mason-lspconfig.nvim",
  --   dependencies = { { "williamboman/mason.nvim", lazy = true, cmd = { "Mason" } } },
  --   lazy = true,
  --   opts = {},
  --   config = true,
  -- },
  -- {
  --   "williamboman/mason.nvim",
  --   lazy = true,
  --   cmd = { "Mason", "MasonUpdate", "MasonInstall", "MasonUninstall", "MasonLog" },
  --   dependencies = {
  --     "williamboman/mason-lspconfig.nvim",
  --     "nvim-lua/plenary.nvim",
  --     "neovim/nvim-lspconfig",
  --     "saghen/blink.cmp",
  --   },
  --   config = function()
  --     require("mason").setup()

  --     require("mason-lspconfig").setup({
  --       ensure_installed = {
  --         "gopls", -- Go
  --         "jdtls", -- Java (requires manual setup, see below)
  --         "ts_ls", -- TypeScript/JavaScript
  --         "terraformls", -- Terraform
  --         "lua_ls", -- Lua
  --         "bashls", -- Bash
  --         "texlab", -- LaTeX
  --       },
  --       automatic_installation = true,
  --       automatic_enable = {
  --         exclude = {
  --           "jdtls",
  --         },
  --       },
  --     })

  --     vim.diagnostic.config({
  --       signs = {
  --         text = {
  --           [vim.diagnostic.severity.ERROR] = "✘",
  --           [vim.diagnostic.severity.WARN] = "▲",
  --           [vim.diagnostic.severity.HINT] = "⚑",
  --           [vim.diagnostic.severity.INFO] = "»",
  --         },
  --       },
  --       virtual_text = true,
  --     })
  --   end,
  --   opts = {
  --     registries = {
  --       "github:nvim-java/mason-registry",
  --       "github:mason-org/mason-registry",
  --     },
  --   },
  -- },
  -- {
  --   "neovim/nvim-lspconfig",
  --   dependencies = { "williamboman/mason-lspconfig.nvim" },
  --   --lazy = true,
  --   event = "VeryLazy",
  --   setup = {
  --     servers = {
  --       basedpyright = {
  --         settings = {
  --           basedpyright = {
  --             analysis = { typeCheckingMode = "standard" },
  --           },
  --         },
  --       },
  --     },
  --   },
  --   config = function()
  --     -- LSP config
  --     vim.api.nvim_exec_autocmds("FileType", {})
  --   end,
  -- },
}
