[window]
padding.x = 16
padding.y = 14
decorations = "none" # Removes the window decoration (title bar, etc.)
option_as_alt = "Both"

[font]
size = 13

# FiraCode Nerd Font
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }

# One Dark theme
[colors]
[colors.primary]
background = '0x1e2127'
foreground = '0xabb2bf'
bright_foreground = '0xe6efff'

# Normal colors
[colors.normal]
black = '0x1e2127'
red = '0xe06c75'
green = '0x98c379'
yellow = '0xd19a66'
blue = '0x61afef'
magenta = '0xc678dd'
cyan = '0x56b6c2'
white = '0x828791'

# Bright colors
[colors.bright]
black = '0x5c6370'
red = '0xe06c75'
green = '0x98c379'
yellow = '0xd19a66'
blue = '0x61afef'
magenta = '0xc678dd'
cyan = '0x56b6c2'
white = '0xe6efff'

# Dim colors
[colors.dim]
black = '0x1e2127'
red = '0xe06c75'
green = '0x98c379'
yellow = '0xd19a66'
blue = '0x61afef'
magenta = '0xc678dd'
cyan = '0x56b6c2'
white = '0x828791'

# Integrate with Zellij
[terminal.shell]
program = "/opt/homebrew/bin/zellij"

[keyboard]
bindings = [
  { key = "V",        mods = "Control|Shift", action = "Paste" },
  { key = "C",        mods = "Control|Shift", action = "Copy" },
  { key = "Paste",                            action = "Paste" },
  { key = "Copy",                             action = "Copy" },
  { key = "Insert",   mods = "Shift",         action = "PasteSelection" },
  { key = "F",        mods = "Control|Shift", action = "SearchForward",     mode = "~Search" },
  { key = "B",        mods = "Control|Shift", action = "SearchBackward",    mode = "~Search" },
  { key = "Key0",     mods = "Control",       action = "ResetFontSize" },
  { key = "Equals",   mods = "Control",       action = "IncreaseFontSize" },
  { key = "Minus",    mods = "Control",       action = "DecreaseFontSize" },
  { key = "L",        mods = "Control",       action = "ClearLogNotice" },
  { key = "L",        mods = "Control",       chars  = "\f" },
  { key = "PageUp",   mods = "Shift",         action = "ScrollPageUp",      mode = "~Alt" },
  { key = "PageDown", mods = "Shift",         action = "ScrollPageDown",    mode = "~Alt" },
  { key = "Up",       mods = "Shift",         action = "ScrollLineUp",      mode = "~Alt" },
  { key = "Down",     mods = "Shift",         action = "ScrollLineDown",    mode = "~Alt" },
  { key = "Home",     mods = "Shift",         action = "ScrollToTop",       mode = "~Alt" },
  { key = "End",      mods = "Shift",         action = "ScrollToBottom",    mode = "~Alt" },
  { key = "Left",     mods = "Alt",     chars = "\u001bb"                      }, # Skip word left
  { key = "Right",    mods = "Alt",     chars = "\u001bf"                      }, # Skip word right
  { key = "Left",     mods = "Command", chars = "\u001bOH", mode = "AppCursor" }, # Home
  { key = "Right",    mods = "Command", chars = "\u001bOF", mode = "AppCursor" }, # End
  { key = "Back",     mods = "Command", chars = "\u0015"                       }, # Delete line
  { key = "Back",     mods = "Alt",     chars = "\u001b\u007f"                 } # Delete word
]
